# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydocker < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/jesseduffield/lazydocker/"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.0/lazydocker_0.21.0_Darwin_x86_64.tar.gz"
      sha256 "0d00faef6cd4569e868bd21742187741fce4458f5b13c498702b2ecd3c1adc35"

      def install
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.0/lazydocker_0.21.0_Darwin_arm64.tar.gz"
      sha256 "78dfcd7a0a0e0fec2ce092ee97d930483eb902f4284a5419fa0bc14f83c6bd7e"

      def install
        bin.install "lazydocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.0/lazydocker_0.21.0_Linux_x86_64.tar.gz"
      sha256 "b81335d0584977b6853c9d671be957f886daa51819efeba2b0a8804ea21b34df"

      def install
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.0/lazydocker_0.21.0_Linux_armv6.tar.gz"
      sha256 "37c7033c721f2b89104d48d8cabba40bb766c1051a54774d3a23b5b8b436506c"

      def install
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.0/lazydocker_0.21.0_Linux_arm64.tar.gz"
      sha256 "a9ad42eed319ef1f958acd944b2044469a0210662084fc41d1df67b54c733f31"

      def install
        bin.install "lazydocker"
      end
    end
  end
end
